Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-02, with the labels that each got.

#1 feat: add tier0_vrfs and tier0_vrf datasource
  .github/workflows/test.yml
  .gitignore
  GNUmakefile
  docs/data-sources/tier0_vrf.md
  docs/data-sources/tier0_vrfs.md
  docs/index.md
  examples/data-sources/cloudavenue_tier0_vrf/data-source.tf
  examples/data-sources/cloudavenue_tier0_vrfs/data-source.tf
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/tier0_vrf_datasource.go
  internal/provider/tier0_vrf_datasource_test.go
  internal/provider/tier0_vrfs_datasource.go
  internal/provider/tier0_vrfs_datasource_test.go
  main.go
  pkg/utils/utils.go
Labels: Feature, Chore, size/XL, Refactor, Fix, CI, category/tools

#4 chore: add vscode configuration
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  GNUmakefile
Labels: Chore, size/M

#2 feat: edge gateways + public ip
  docs/data-sources/edge_gateway.md
  docs/data-sources/edge_gateways.md
  docs/data-sources/public_ip.md
  examples/data-sources/cloudavenue_edge_gateways/data-source.tf
  examples/data-sources/cloudavenue_public_ip/data-source.tf
  internal/provider/edge_gateway_datasource.go
  internal/provider/edge_gateway_datasource_test.go
  internal/provider/edge_gateways_datasource.go
  internal/provider/edge_gateways_datasource_test.go
  internal/provider/provider.go
  internal/provider/public_ip_datasource.go
  internal/provider/public_ip_datasource_test.go
  main.go
Labels: Feature, size/XL

#6 feat: vdcs
  docs/data-sources/vdc.md
  docs/data-sources/vdcs.md
  examples/data-sources/cloudavenue_vdc/data-source.tf
  examples/data-sources/cloudavenue_vdcs/data-source.tf
  internal/provider/provider.go
  internal/provider/vdc_datasource.go
  internal/provider/vdc_datasource_test.go
  internal/provider/vdcs_datasource.go
  internal/provider/vdcs_datasource_test.go
Labels: Feature, size/XL

#12 feat: generic func for uuid gen
  internal/provider/tier0_vrf_datasource.go
  internal/provider/tier0_vrfs_datasource.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: Feature, size/M

#10 ci: play acceptance tests only with slash command
  .github/workflows/test.yml
  .github/workflows/testacc.yml
Labels: size/L, CI

#11 chore: add issue and PR templates
  .github/ISSUE_TEMPLATE/00_bug_report.yml
  .github/ISSUE_TEMPLATE/01_documentation.yml
  .github/ISSUE_TEMPLATE/02_enhancement.yml
  .github/ISSUE_TEMPLATE/03_new_resource.yml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: Chore, size/L

#27 chore(lint): fix golang lint errors
  .golangci.yml
  .vscode/settings.json
  internal/provider/edge_gateway_datasource.go
  internal/provider/edge_gateways_datasource.go
  internal/provider/helper_api_errors.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/tier0_vrf_datasource.go
  internal/provider/vdc_datasource.go
  internal/provider/vdcs_datasource.go
  main.go
Labels: Chore, size/L, category/lint

#26 feat: edge gateway resource
  docs/resources/edge_gateway.md
  examples/resources/cloudavenue_edge_gateway/import.sh
  examples/resources/cloudavenue_edge_gateway/resource.tf
  go.mod
  go.sum
  internal/provider/edge_gateway_resource.go
  internal/provider/helper_auth.go
  internal/provider/helper_auth_test.go
  internal/provider/helper_job.go
  internal/provider/provider.go
Labels: Feature, size/L, Refactor, Fix

#32 fix: lint error
  internal/provider/edge_gateway_resource.go
  internal/provider/helper_auth.go
  internal/provider/helper_auth_test.go
Labels: Fix, size/S

#31 feat: add vdc resource
  docs/resources/vdc.md
  examples/resources/cloudavenue_vdc/import.sh
  examples/resources/cloudavenue_vdc/resource.tf
  internal/provider/edge_gateway_resource.go
  internal/provider/helper_job.go
  internal/provider/provider.go
  internal/provider/vdc_resource.go
Labels: Feature, Chore, size/XL, Fix, Docs, category/vdc, category/helper

#33 feat(publicip): add resource `cloudavenue_public_ip`
  docs/resources/public_ip.md
  examples/resources/cloudavenue_public_ip/import.sh
  examples/resources/cloudavenue_public_ip/resource.tf
  internal/provider/provider.go
  internal/provider/public_ip_datasource.go
  internal/provider/public_ip_resource.go
Labels: Feature, size/XL, Fix, category/publicip

#40 fix: create edge_gateway_resource + tests
  internal/provider/edge_gateway_resource.go
  internal/provider/edge_gateway_resource_test.go
  internal/provider/helper_job.go
  internal/provider/public_ip_resource.go
  internal/provider/vdc_resource.go
Labels: size/L, Fix

#39 docs: add Cloud Avenue documentation links
  docs/index.md
  docs/resources/vcda_ip.md
  docs/resources/vdc.md
  internal/provider/vcda_ip_resource.go
  internal/provider/vdc_resource.go
  templates/index.md.tmpl
Labels: Docs, size/S

#44 refactor: internal directories and files
  go.mod
  internal/client/client.go
  internal/client/client_test.go
  internal/helpers/api_errors.go
  internal/helpers/auth.go
  internal/helpers/auth_test.go
  internal/helpers/config.go
  internal/helpers/job.go
  internal/provider/edgegw/edge_gateway_datasource.go
  internal/provider/edgegw/edge_gateway_resource.go
  internal/provider/edgegw/edge_gateways_datasource.go
  internal/provider/helper_job.go
  internal/provider/provider.go
  internal/provider/publicip/public_ip_datasource.go
  internal/provider/publicip/public_ip_resource.go
  internal/provider/vcda/vcda_ip_resource.go
  internal/provider/vdc/vdc_datasource.go
  internal/provider/vdc/vdc_resource.go
  internal/provider/vdc/vdcs_datasource.go
  internal/provider/vrf/tier0_vrf_datasource.go
  internal/provider/vrf/tier0_vrfs_datasource.go
  internal/tests/acctest.go
  internal/tests/edge_gateway_datasource_test.go
  internal/tests/edge_gateway_resource_test.go
  internal/tests/edge_gateways_datasource_test.go
  internal/tests/public_ip_datasource_test.go
  internal/tests/tier0_vrf_datasource_test.go
  internal/tests/tier0_vrfs_datasource_test.go
  internal/tests/vdc_datasource_test.go
  internal/tests/vdcs_datasource_test.go
Labels: size/XL, Refactor

#46 chore(deps): update cloudavenue-sdk from 0.0.3 to 0.1.0
  go.mod
  go.sum
  internal/client/client.go
  internal/helpers/job.go
  internal/provider/edgegw/edge_gateway_datasource.go
  internal/provider/edgegw/edge_gateway_resource.go
  internal/provider/edgegw/edge_gateways_datasource.go
  internal/provider/publicip/public_ip_datasource.go
  internal/provider/publicip/public_ip_resource.go
  internal/provider/vcda/vcda_ip_resource.go
  internal/provider/vdc/vdc_datasource.go
  internal/provider/vdc/vdc_resource.go
  internal/provider/vdc/vdcs_datasource.go
  internal/provider/vrf/tier0_vrf_datasource.go
  internal/provider/vrf/tier0_vrfs_datasource.go
Labels: Feature, Chore, size/M, category/deps

#47 feat: import edge gateway by name
  internal/provider/edgegw/edge_gateway_resource.go
Labels: Feature, size/S

#50 test(tf): add import test on edgegateway resource
  internal/tests/edge_gateway_resource_test.go
Labels: Test, size/S, category/tf

#56 chore(helper): add helper stringpm `Default` (#55)
  go.mod
  go.sum
  internal/helpers/stringpm/README.md
  internal/helpers/stringpm/default.go
  internal/helpers/stringpm/default_test.go
Labels: Chore, size/L, category/helper

#60 chore(helper): add helper stringpm `DefaultEnvVar` (#59)
  internal/helpers/stringpm/README.md
  internal/helpers/stringpm/default_env_var.go
  internal/helpers/stringpm/default_env_var_test.go
Labels: Chore, size/L, category/helper

#64 feat(catalog): add resource `cloudavenue_catalog`
  docs/resources/catalog.md
  examples/resources/cloudavenue_catalog/import.sh
  examples/resources/cloudavenue_catalog/resource.tf
  internal/provider/catalog/catalog_datasource.go
  internal/provider/catalog/catalog_resource.go
  internal/provider/provider.go
  internal/tests/catalog_resource_test.go
Labels: Feature, size/XL, category/catalog

#72 feat(org): Add resource `cloudavenue_org_user`
  docs/resources/org_user.md
  examples/resources/cloudavenue_org_user/import.sh
  examples/resources/cloudavenue_org_user/resource.tf
  internal/provider/catalog/catalog_resource.go
  internal/provider/org/user_resource.go
  internal/provider/provider.go
  internal/tests/org_user_test.go
Labels: Feature, size/XL, category/org

#75 chore(helper): add PlanModifier boolean `SetDefault...`
  internal/helpers/boolpm/README.md
  internal/helpers/boolpm/base_default_func.go
  internal/helpers/boolpm/default.go
  internal/helpers/boolpm/default_env_var.go
  internal/helpers/boolpm/default_env_var_test.go
  internal/helpers/boolpm/default_func.go
  internal/helpers/boolpm/default_func_test.go
  internal/helpers/boolpm/default_test.go
Labels: Chore, size/XL, category/helper

#86 feat: add go generate tf-doc-extractor
  .github/workflows/test.yml
  GNUmakefile
Labels: Feature, size/XS

#82 feat(org): Add DataSource `cloudavenue_org_user`
  docs/data-sources/org_user.md
  examples/data-sources/cloudavenue_org_user/data-source.tf
  internal/provider/org/user_datasource.go
  internal/provider/provider.go
  internal/tests/org_user_datasource_test.go
  internal/tests/org_user_resource_test.go
Labels: Feature, size/L, category/org

#88 feat(org): Add DataSource `cloudavenue_catalog`
  docs/data-sources/catalog.md
  examples/data-sources/cloudavenue_catalog/data-source.tf
  internal/provider/catalog/catalog_datasource.go
  internal/provider/provider.go
  internal/tests/catalog_datasource_test.go
Labels: Feature, size/L, category/org

#92 feat(org): Add DataSource `cloudavenue_catalogs`
  docs/data-sources/catalogs.md
  examples/data-sources/cloudavenue_catalogs/data-source.tf
  internal/provider/catalog/catalog.go
  internal/provider/catalog/catalogs_datasource.go
  internal/provider/provider.go
  internal/tests/catalogs_datasource_test.go
Labels: Feature, size/L, category/org

#104 feat(org): Add resource `cloudavenue_org_role`
  docs/resources/org_role.md
  examples/resources/cloudavenue_org_role/import.sh
  examples/resources/cloudavenue_org_role/resource.tf
  internal/provider/org/role_resource.go
  internal/provider/provider.go
  internal/tests/org_role_resource_test.go
Labels: Feature, size/XL, Test, category/org

#98 feat(org): Add DataSource `cloudavenue_catalog_vapp_template`
  docs/data-sources/catalog_vapp_template.md
  examples/data-sources/cloudavenue_catalog_vapp_template/data-source.tf
  internal/provider/catalog/catalog_datasource.go
  internal/provider/catalog/catalog_vapp_template_datasource.go
  internal/provider/provider.go
  internal/tests/catalog_vapp_template_datasource_test.go
Labels: Feature, size/L, category/org

#97 feat(org): add datasource `cloudvanue_org_group`
  docs/data-sources/org_group.md
  examples/data-sources/cloudavenue_org_group/data-source.tf
  internal/provider/org/group_datasource.go
  internal/provider/provider.go
  internal/tests/org_group_datasource_test.go
Labels: Feature, size/L, category/org

#106 chore(lint): add `VDC` in var-naming lint
  .golangci.yml
  internal/client/client.go
  internal/client/client_test.go
  internal/client/vmware.go
  internal/provider/provider.go
  internal/provider/publicip/public_ip_resource.go
  internal/provider/vapp/vapp_datasource.go
  internal/provider/vapp/vapp_resource.go
  internal/provider/vdc/vdc_datasource.go
  internal/provider/vdc/vdc_resource.go
  internal/provider/vdc/vdcs_datasource.go
  internal/tests/vdc_datasource_test.go
  internal/tests/vdcs_datasource_test.go
Labels: Chore, size/L, category/lint

#109 ci: restrict lint and generate diff on PR
  .github/workflows/test.yml
Labels: CI, size/XS

#108 chore: add code snippets
  .vscode/terraform.code-snippets
Labels: Chore, size/S

#105 feat(vapp): Add resource `cloudavenue_vapp_vm_internal_disk`
  docs/resources/vapp_vm_internal_disk.md
  examples/resources/cloudavenue_vapp_vm_internal_disk/resource.tf
  examples/resources/cloudavenue_vm_internal_disk/import.sh
  examples/resources/cloudavenue_vm_internal_disk/resource.tf
  internal/provider/common/mutex/mutex.go
  internal/provider/common/vapp/vapp.go
  internal/provider/common/vm/disk.go
  internal/provider/common/vm/vm.go
  internal/provider/provider.go
  internal/provider/vapp/vm_internal_disk_resource.go
  internal/tests/vapp_vm_internal_disk_resource_test.go
Labels: Feature, size/XL, category/vapp

#114 refactor(vapp): replace deprecated Blocks
  docs/resources/vapp_vm_internal_disk.md
  examples/resources/cloudavenue_vapp_vm_internal_disk/resource.tf
  internal/provider/vapp/vm_internal_disk_resource.go
  internal/tests/vapp_vm_internal_disk_resource_test.go
Labels: Refactor, size/S, category/vapp, category/vapp_vm_internal_disk

#111 feat(org): Add data source `cloudavenue_org_role`
  docs/data-sources/org_role.md
  examples/data-sources/cloudavenue_org_role/data-source.tf
  internal/provider/org/role_datasource.go
  internal/provider/provider.go
  internal/tests/org_role_datasource_test.go
Labels: Feature, size/L, Test, category/org

#117 chore: add draft `cloudavenue_vm`
  internal/provider/common/vm/customization.go
  internal/provider/common/vm/disk.go
  internal/provider/common/vm/diskparams/bus_number.go
  internal/provider/common/vm/diskparams/bus_type.go
  internal/provider/common/vm/diskparams/size_in_mb.go
  internal/provider/common/vm/diskparams/storage_profile.go
  internal/provider/common/vm/diskparams/unit_number.go
  internal/provider/common/vm/internal_disk.go
  internal/provider/common/vm/network.go
  internal/provider/common/vm/os_type.go
  internal/provider/common/vm/resource.go
  internal/provider/common/vm/template_disk.go
  internal/provider/provider.go
  internal/provider/vapp/vapp.go
  internal/provider/vm/common_vm.go
  internal/provider/vm/common_vm_create.go
  internal/provider/vm/common_vm_read.go
  internal/provider/vm/common_vm_schema.go
  internal/provider/vm/common_vm_update.go
  internal/provider/vm/vm_resource.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: Chore, size/XL

#115 feat: upgrade Golang version to 1.20
  .github/workflows/release.yml
  GNUmakefile
  README.md
  go.mod
  go.sum
Labels: Feature, size/M

#124 feat(vapp): add resource cloudavenue_vapp_org_network
  docs/resources/vapp_org_network.md
  examples/resources/cloudavenue_vapp_org_network/import.sh
  examples/resources/cloudavenue_vapp_org_network/resource.tf
  internal/provider/common/common.go
  internal/provider/provider.go
  internal/provider/vapp/common_org_network.go
  internal/provider/vapp/org_network_resource.go
  internal/tests/vapp/org_network_resource_test.go
  templates/resources/vapp_org_network.md.tmpl
Labels: Feature, size/XL, category/vapp
