Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-09, with the labels that each got.

#496 test: Catalog acceptances tests refactor
  internal/testsacc/acctest.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/catalog_acl_datasource_test.go
  internal/testsacc/catalog_acl_resource_test.go
  internal/testsacc/catalog_resource_test.go
  internal/testsacc/iam_user_resource_test.go
Labels: Feature, size/M, Test

#495 feat: add generic interface constrains for testsacc
  go.mod
  internal/helpers/testsacc/testsacc.go
  internal/testsacc/acctest.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/catalog_acl_datasource_test.go
  internal/testsacc/catalog_acl_resource_test.go
  internal/testsacc/catalog_resource_test.go
  internal/testsacc/iam_user_resource_test.go
Labels: Feature, size/L, Test

#515 fix: error VDC group name cannot be update in vcd resource
  .changelog/511.txt
  go.mod
  internal/provider/vdc/vdc_resource.go
Labels: Fix, size/XS

#518 fix: bug to impossible to update a vcd resource without a resource vcd_group define
  .changelog/518.txt
  go.mod
  go.sum
  internal/provider/vdc/vdc_resource.go
Labels: Chore, Fix, size/XS

#521 fix: update testacc vdcgroup and vdc resource
  .changelog/521.txt
  internal/provider/vdc/vdc_resource.go
  internal/testsacc/vdc_resource_test.go
Labels: Fix, size/XS

#523 chore: Downgrade Go version
  go.mod
  go.sum
Labels: Chore, size/XS, category/ci

#525 feat: add generate template for testsacc
  go.mod
  go.sum
  internal/helpers/testsacc/template.go
  internal/helpers/testsacc/testsacc.go
  internal/testsacc/acctest.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/catalog_resource_test.go
  internal/testsacc/edgegw_edgegateway_resource_test.go
  internal/testsacc/tier0_vrf_datasource_test.go
  internal/testsacc/vdc_resource_test.go
Labels: Feature, size/L

#535 chore: move to new testsacc framework
  docs/resources/vapp.md
  examples/resources/cloudavenue_vapp/import.sh
  internal/helpers/testsacc/testsacc.go
  internal/provider/vapp/vapp_resource.go
  internal/testsacc/acctest.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/catalog_acl_datasource_test.go
  internal/testsacc/catalog_acl_resource_test.go
  internal/testsacc/catalog_resource_test.go
  internal/testsacc/edgegw_edgegateway_resource_test.go
  internal/testsacc/network_routed_resource_test.go
  internal/testsacc/tier0_vrf_datasource_test.go
  internal/testsacc/vapp_org_network_resource_test.go
  internal/testsacc/vapp_resource_test.go
  internal/testsacc/vdc_resource_test.go
  templates/resources/vapp.md.tmpl
Labels: Chore, size/L

#532 fix: Bug VDC attributes unchangeables
  .changelog/524.txt
  docs/resources/vdc.md
  internal/provider/vdc/vdc_schema.go
Labels: Fix, size/XS

#537 fix: add `vapp_id` attribut in `cloudavenue_vapp_org_network`
  internal/provider/vapp/org_network_resource.go
Labels: Fix, size/XS

#539 fix: changelog message for PR524
  .changelog/524.txt
Labels: Fix, size/XS

#536 feat: Change attribute field for import resource by EdgeGatewayName or EdgeGatewayID. (#525)
  .changelog/526.txt
  docs/resources/network_routed.md
  examples/resources/cloudavenue_network_routed/import.sh
  internal/helpers/testsacc/testsacc.go
  internal/provider/network/routed_resource.go
  internal/testsacc/acctest.go
  internal/testsacc/network_routed_resource_test.go
Labels: Feature, Refactor, size/S

#540 fix!: remove attributs `is_fenced` and `retain_ip_mac_enabled`
  .changelog/538.txt
  docs/data-sources/vapp_org_network.md
  docs/resources/vapp_org_network.md
  internal/provider/common/network/schema.go
  internal/provider/vapp/org_network_datasource.go
  internal/provider/vapp/org_network_resource.go
  internal/provider/vapp/vapp_types.go
  internal/testsacc/acctest.go
  internal/testsacc/vapp_org_network_datasource_test.go
  internal/testsacc/vapp_org_network_resource_test.go
Labels: Fix, size/M, BreakingChange

#542 chore: fix wrong value in documentation for vdc attributes
  .changelog/530.txt
  docs/resources/vdc.md
  internal/provider/vdc/base.go
  internal/provider/vdc/vdc_datasource.go
  internal/provider/vdc/vdc_resource.go
  internal/provider/vdc/vdc_schema.go
  internal/provider/vdc/vdc_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/vdc_datasource_test.go
Labels: Chore, Refactor, size/M

#547 feat: Add Netbackup client available
  .changelog/546.txt
  docs/index.md
  go.mod
  go.sum
  internal/client/client.go
  internal/provider/provider.go
  internal/provider/provider_schema.go
  internal/provider/provider_types.go
Labels: Feature, size/M

#549 docs: Improve documentation for provider authentication and config
  .changelog/548.txt
  docs/index.md
  internal/client/client.go
  internal/client/netbackup.go
  internal/provider/provider.go
  templates/index.md.tmpl
Labels: size/M, Docs
