Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-08, with the labels that each got.

#433 chore: re-organize provider files
  .github/workflows/generate_listing.yml
  internal/provider/provider.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/provider/provider_schema.go
  internal/provider/provider_types.go
Labels: Chore, size/M

#440 ci: Add Acceptance Tests
  .github/workflows/testacc.yml
Labels: CI, size/S

#441 chore: upgrade `cloudavenue_vm_inserted_media` to superSchema
  .vscode/terraform.code-snippets
  docs/resources/vm_inserted_media.md
  internal/provider/common/vm/vm.go
  internal/provider/provider_resources.go
  internal/provider/vm/inserted_media_resource.go
  internal/provider/vm/inserted_media_schema.go
  internal/provider/vm/inserted_media_types.go
  internal/tests/vapp/vapp_resource_test.go
  internal/tests/vm/inserted_media_resource_test.go
  internal/tests/vm/vm_resource_test.go
Labels: Chore, size/M

#449 chore(ci): integrate terraform fmt into generate
  GNUmakefile
Labels: Chore, size/XS, category/ci

#451 chore: Format terraform example files / docs
  .changelog/451.txt
  docs/data-sources/edgegateway_nat_rule.md
  docs/data-sources/vapp_isolated_network.md
  docs/data-sources/vm.md
  docs/resources/catalog.md
  examples/data-sources/cloudavenue_edgegateway_nat_rule/data-source.tf
  examples/data-sources/cloudavenue_vapp_isolated_network/data-source.tf
  examples/data-sources/cloudavenue_vm/data-source.tf
  examples/resources/cloudavenue_catalog/resource.tf
  examples/resources/resource.tf
Labels: Chore, size/S

#455 ci: Add Acceptance Tests
  .github/workflows/testacc.yml
Labels: CI, size/XS

#456 ci: testacc enhancement
  .github/workflows/testacc.yml
Labels: CI, size/XS

#457 ci: Fix Acceptance Tests
  .github/workflows/testacc.yml
Labels: CI, size/XS

#460 ci: Fix testacc.yml
  .github/workflows/testacc.yml
Labels: CI, size/XS

#452 feat: add `cloudavenue_vdc_group` resource
  .changelog/445.txt
  .changelog/448.txt
  .github/workflows/testacc.yml
  docs/data-sources/vdc.md
  docs/resources/vdc.md
  docs/resources/vdc_group.md
  examples/resources/cloudavenue_vdc_group/resource.tf
  go.mod
  go.sum
  internal/provider/common/adminorg/vdc_group.go
  internal/provider/provider_resources.go
  internal/provider/vdc/vdc_group_datasource_types.go
  internal/provider/vdc/vdc_group_resource.go
  internal/provider/vdc/vdc_group_resource_types.go
  internal/provider/vdc/vdc_group_schema.go
  internal/provider/vdc/vdc_group_schema_test.go
  internal/provider/vdc/vdc_resource.go
  internal/provider/vdc/vdc_schema.go
  internal/tests/vdc/vdc_group_resource_test.go
  internal/tests/vdc/vdc_resource_test.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
  templates/resources/vdc_group.md.tmpl
Labels: Feature, size/XL

#463 chore: migrate `cloudavenue_(catalogs/catalog_vapp_template)` to superschema
  .changelog/443.txt
  .github/workflows/testacc.yml
  docs/data-sources/catalog_vapp_template.md
  docs/data-sources/catalogs.md
  internal/provider/catalog/catalog_schema.go
  internal/provider/catalog/catalog_vapp_template_datasource.go
  internal/provider/catalog/catalog_vapp_template_schema.go
  internal/provider/catalog/catalog_vapp_template_types.go
  internal/provider/catalog/catalogs_datasource.go
  internal/provider/catalog/catalogs_schema.go
  internal/provider/edgegw/ip_set_resource.go
  internal/tests/catalog/catalog_vapp_template_datasource_test.go
  internal/tests/catalog/catalogs_datasource_test.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
Labels: Chore, size/L, Fix

#467 chore: Update listing
  cmd/listing/main.go
  cmd/listing/resource-ca.md
Labels: Chore, size/M, category/script

#473 fix: Revert bump hashicorp/terraform-plugin-framework-validators from 0.10.0 to 0.11.0
  .changelog/462.txt
  go.mod
  go.sum
Labels: Fix, size/XS

#471 feat: add `cloudavenue_catalog_acl` resource
  .changelog/453.txt
  .changelog/472.txt
  docs/data-sources/catalog_acl.md
  docs/resources/catalog_acl.md
  examples/data-sources/cloudavenue_catalog_acl/data-source.tf
  examples/resources/cloudavenue_catalog_acl/import.sh
  internal/provider/catalog/acl_datasource.go
  internal/provider/catalog/acl_resource.go
  internal/provider/catalog/acl_schema.go
  internal/provider/catalog/acl_types.go
  internal/provider/catalog/base.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/tests/catalog/acl_datasource_test.go
  internal/tests/catalog/acl_resource_test.go
  internal/tests/catalog/catalog_resource_test.go
  internal/tests/iam/iam_user_datasource_test.go
  internal/tests/iam/iam_user_resource_test.go
  templates/data-sources/catalog_acl.md.tmpl
  templates/resources/catalog_acl.md.tmpl
Labels: Feature, size/XL

#479 feat: add `cloudavenue_vm_disks` datasource
  .changelog/475.txt
  .changelog/478.txt
  docs/data-sources/vm_disks.md
  docs/resources/vm_disk.md
  examples/data-sources/cloudavenue_vm_disks/data-source.tf
  internal/provider/provider_datasources.go
  internal/provider/vm/vm_disk_schema.go
  internal/provider/vm/vm_disks_datasource.go
  internal/provider/vm/vm_disks_schema.go
  internal/provider/vm/vm_disks_types.go
  internal/tests/vm/vm_disk_resource_test.go
  internal/tests/vm/vm_disks_datasource_test.go
  templates/data-sources/vm_disks.md.tmpl
Labels: Feature, size/L, Fix

#486 docs: fix example in `cloudavenue_vdc` resource
  .changelog/481.txt
  docs/resources/vdc.md
  examples/resources/cloudavenue_vdc/resource.tf
Labels: size/XS, Docs

#485 fix: error message in ImportFunc (#482)
  internal/provider/edgegw/nat_rule_resource.go
Labels: Fix, size/XS

#484 feat: add `cloudavenue_iam_token` resource
  .changelog/423.txt
  docs/resources/iam_token.md
  examples/resources/cloudavenue_iam_token/resource.tf
  internal/provider/iam/token_resource.go
  internal/provider/iam/token_schema.go
  internal/provider/iam/token_types.go
  internal/provider/provider_resources.go
  internal/tests/iam/token_resource_test.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
  templates/resources/iam_token.md.tmpl
Labels: Feature, size/L

#483 feat: add import for `cloudavenue_vm_disk` (#344) and fix (#480)
  .changelog/344.txt
  .changelog/480.txt
  docs/resources/vm_disk.md
  examples/resources/cloudavenue_vm_disk/resource.tf
  internal/provider/vm/vm_disk_resource.go
  internal/provider/vm/vm_disk_schema.go
  internal/tests/vm/vm_disk_resource_test.go
  templates/resources/vm_disk.md.tmpl
Labels: Feature, Chore, size/M

#488 chore: migrate `cloudavenue_edgegateways` datasource to superschema
  docs/data-sources/edgegateways.md
  internal/provider/edgegw/edgegateways_datasource.go
  internal/provider/edgegw/edgegateways_schema.go
  internal/provider/edgegw/edgegateways_types.go
  internal/tests/edgegw/edgegateways_datasource_test.go
Labels: Chore, size/M

#474 feat: Add resource/datasource `cloudavenue_edgegateway_ipsec_vpn_tunnel`
  .changelog/352.txt
  .changelog/353.txt
  .github/workflows/testacc.yml
  .golangci.yml
  docs/data-sources/edgegateway_vpn_ipsec.md
  docs/resources/edgegateway_vpn_ipsec.md
  examples/data-sources/cloudavenue_edgegw_vpn_ipsec/data-source.tf
  examples/resources/cloudavenue_edgegateway_vpn_ipsec/import.sh
  internal/provider/edgegw/vpn_ipsec_datasource.go
  internal/provider/edgegw/vpn_ipsec_resource.go
  internal/provider/edgegw/vpn_ipsec_schema.go
  internal/provider/edgegw/vpn_ipsec_schema_test.go
  internal/provider/edgegw/vpn_ipsec_types.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/tests/edgegw/vpn_ipsec_datasource_test.go
  internal/tests/edgegw/vpn_ipsec_resource_test.go
  templates/data-sources/edgegateway_vpn_ipsec.md.tmpl
  templates/resources/edgegateway_vpn_ipsec.md.tmpl
Labels: Feature, size/XL

#500 chore: bump FrangipaneTeam/terraform-plugin-framework-superschema
  .changelog/500.txt
  go.mod
  go.sum
  internal/provider/edgegw/nat_rule_types.go
  internal/provider/edgegw/static_route_types.go
  internal/provider/edgegw/vpn_ipsec_resource.go
  internal/provider/edgegw/vpn_ipsec_types.go
  internal/provider/network/dhcp_binding_resource.go
  internal/provider/network/dhcp_binding_types.go
Labels: Chore, size/XS

#501 chore: improve types generator
  cmd/types-generator/main.go
Labels: Chore, size/S
