Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-10, with the labels that each got.

#551 fix: testAcc Get checks from resource to datasource
  internal/helpers/testsacc/template.go
  internal/helpers/testsacc/testsacc.go
  internal/testsacc/acctest.go
  internal/testsacc/vdc_datasource_test.go
Labels: Fix, size/S

#553 chore: add generate docs for planmodifier RequireReplaceIf
  .changelog/533.txt
  docs/resources/vdc.md
  docs/resources/vm_disk.md
  go.mod
  go.sum
  internal/provider/vdc/vdc_schema.go
Labels: Chore, size/XS

#554 chore: move `vdc_group` datasource to superschema
  .changelog/442.txt
  docs/data-sources/vdc_group.md
  docs/resources/vdc_group.md
  examples/data-sources/cloudavenue_vdc_group/data-source.tf
  examples/resources/cloudavenue_vdc_group/import.sh
  examples/resources/cloudavenue_vdc_group/resource.tf
  internal/provider/provider_datasources.go
  internal/provider/vdc/vdc_group_datasource.go
  internal/provider/vdc/vdc_group_datasource_types.go
  internal/provider/vdc/vdc_group_resource.go
  internal/provider/vdc/vdc_group_schema.go
  internal/provider/vdc/vdc_group_schema_test.go
  internal/provider/vdc/vdc_group_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/vdc_group_datasource_test.go
  internal/testsacc/vdc_group_resource_test.go
  internal/testsacc/vdc_resource_test.go
Labels: Chore, size/L

#555 chore: testsacc support TFAdvanced
  internal/helpers/job.go
  internal/helpers/testsacc/testsacc.go
  internal/provider/vdc/vdc_resource.go
  internal/testsacc/vdc_group_resource_test.go
  internal/testsacc/vdc_resource_test.go
Labels: Chore, size/M

#556 chore: migrate cloudavenue sdk to infrapi
  .golangci.yml
  go.mod
  go.sum
  internal/client/client.go
  internal/client/client_test.go
  internal/helpers/api_errors.go
  internal/helpers/auth.go
  internal/helpers/auth_test.go
  internal/provider/edgegw/edgegateway_datasource.go
  internal/provider/edgegw/edgegateway_resource.go
  internal/provider/publicip/publicip_resource.go
  internal/provider/vdc/vdc_resource.go
Labels: Chore, size/XS

#558 feat: New resource/datasource `cloudavenue_backup`
  .changelog/558.txt
  cmd/types-generator/main.go
  docs/data-sources/backup.md
  docs/resources/backup.md
  examples/data-sources/cloudavenue_backup/data-source.tf
  examples/resources/cloudavenue_backup/import.sh
  go.mod
  go.sum
  internal/client/client.go
  internal/client/netbackup.go
  internal/provider/backup/backup_datasource.go
  internal/provider/backup/backup_resource.go
  internal/provider/backup/backup_schema.go
  internal/provider/backup/backup_schema_test.go
  internal/provider/backup/backup_types.go
  internal/provider/backup/base.go
  internal/provider/provider.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/backup_datasource_test.go
  internal/testsacc/backup_resource_test.go
  internal/testsacc/vdc_acl_resource_test.go
  templates/data-sources/backup.md.tmpl
  templates/resources/backup.md.tmpl
Labels: Feature, size/XL, Fix

#563 chore: bump VCD API Version from 37.1 to 37.2
  .changelog/562.txt
  internal/provider/provider.go
Labels: Chore, size/XS

#570 fix: resource name for stats
  internal/provider/backup/backup_datasource.go
Labels: Fix, size/XS

#573 feat: add bandwidth and deprecate lb_enabled attributes on _edgegateway
  .changelog/567.txt
  .changelog/568.txt
  docs/data-sources/edgegateway.md
  docs/resources/edgegateway.md
  examples/resources/cloudavenue_edgegateway/resource.tf
  go.mod
  go.sum
  internal/client/client.go
  internal/provider/backup/backup_datasource.go
  internal/provider/backup/backup_resource.go
  internal/provider/edgegw/edgegateway_datasource.go
  internal/provider/edgegw/edgegateway_resource.go
  internal/provider/edgegw/edgegateway_schema.go
  internal/provider/edgegw/edgegateway_types.go
  internal/provider/provider.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/edgegw_edgegateway_datasource_test.go
  internal/testsacc/edgegw_edgegateway_resource_test.go
Labels: Feature, size/XL

#586 feat: add `cloudavenue_s3_bucket` resource/datasource
  .changelog/576.txt
  docs/data-sources/s3_bucket.md
  docs/resources/s3_bucket.md
  examples/data-sources/cloudavenue_s3_bucket/data-source.tf
  examples/resources/cloudavenue_s3_bucket/import.sh
  examples/resources/cloudavenue_s3_bucket/resource.tf
  go.mod
  go.sum
  internal/helpers/testsacc/template.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/provider/s3/base.go
  internal/provider/s3/bucket_datasource.go
  internal/provider/s3/bucket_resource.go
  internal/provider/s3/bucket_schema.go
  internal/provider/s3/bucket_schema_test.go
  internal/provider/s3/bucket_types.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/s3_bucket_datasource_test.go
  internal/testsacc/s3_bucket_resource_test.go
  templates/data-sources/s3_bucket.md.tmpl
  templates/resources/s3_bucket.md.tmpl
Labels: Feature, size/L

#590 feat: add `cloudavenue_s3_bucket_versioning_configuration` resource/d…
  .changelog/584.txt
  docs/data-sources/s3_bucket_versioning_configuration.md
  docs/resources/s3_bucket_versioning_configuration.md
  examples/data-sources/cloudavenue_s3_bucket_versioning_configuration/data-source.tf
  examples/resources/cloudavenue_s3_bucket_versioning_configuration/import.sh
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/provider/s3/bucket_versioning_configuration_datasource.go
  internal/provider/s3/bucket_versioning_configuration_resource.go
  internal/provider/s3/bucket_versioning_configuration_schema.go
  internal/provider/s3/bucket_versioning_configuration_schema_test.go
  internal/provider/s3/bucket_versioning_configuration_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/s3_bucket_versioning_configuration_datasource_test.go
  internal/testsacc/s3_bucket_versioning_configuration_resource_test.go
  pkg/utils/utils.go
  templates/data-sources/s3_bucket_versioning_configuration.md.tmpl
  templates/resources/s3_bucket_versioning_configuration.md.tmpl
Labels: Feature, size/L

#594 fix: multi testsacc error
  .golangci.yml
  internal/helpers/testsacc/testsacc.go
  internal/testsacc/acctest.go
  internal/testsacc/backup_datasource_test.go
  internal/testsacc/backup_resource_test.go
  internal/testsacc/catalog_acl_datasource_test.go
  internal/testsacc/catalog_acl_resource_test.go
  internal/testsacc/catalog_resource_test.go
  internal/testsacc/edgegw_edgegateway_datasource_test.go
  internal/testsacc/edgegw_edgegateway_resource_test.go
  internal/testsacc/network_routed_resource_test.go
  internal/testsacc/s3_bucket_cors_configuration_datasource_test.go
  internal/testsacc/s3_bucket_cors_configuration_resource_test.go
  internal/testsacc/s3_bucket_datasource_test.go
  internal/testsacc/s3_bucket_resource_test.go
  internal/testsacc/s3_bucket_versioning_configuration_datasource_test.go
  internal/testsacc/s3_bucket_versioning_configuration_resource_test.go
  internal/testsacc/tier0_vrf_datasource_test.go
  internal/testsacc/vapp_org_network_resource_test.go
  internal/testsacc/vapp_resource_test.go
  internal/testsacc/vdc_datasource_test.go
  internal/testsacc/vdc_group_datasource_test.go
  internal/testsacc/vdc_group_resource_test.go
  internal/testsacc/vdc_resource_test.go
Labels: Fix, size/M

#602 feat: add `cloudavenue_s3_bucket_lifecycle_configuration`
  .changelog/579.txt
  docs/data-sources/s3_bucket_lifecycle_configuration.md
  docs/resources/s3_bucket_lifecycle_configuration.md
  examples/data-sources/cloudavenue_s3_bucket_lifecycle_configuration/data-source.tf
  examples/resources/cloudavenue_s3_bucket_lifecycle_configuration/import.sh
  go.mod
  go.sum
  internal/helpers/testsacc/testsacc.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/provider/s3/base.go
  internal/provider/s3/bucket_lifecycle_configuration_datasource.go
  internal/provider/s3/bucket_lifecycle_configuration_resource.go
  internal/provider/s3/bucket_lifecycle_configuration_schema.go
  internal/provider/s3/bucket_lifecycle_configuration_schema_test.go
  internal/provider/s3/bucket_lifecycle_configuration_types.go
  internal/testsacc/acctest.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/s3_bucket_lifecycle_configuration_datasource_test.go
  internal/testsacc/s3_bucket_lifecycle_configuration_resource_test.go
  internal/testsacc/s3_bucket_versioning_configuration_resource_test.go
  templates/data-sources/s3_bucket_lifecycle_configuration.md.tmpl
  templates/resources/s3_bucket_lifecycle_configuration.md.tmpl
Labels: Feature, size/XL, Fix
