Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-11, with the labels that each got.

#607 feat: add `cloudavenue_s3_bucket_website_configuration`
  .changelog/587.txt
  cmd/types-generator/go.sum
  docs/data-sources/s3_bucket_website_configuration.md
  docs/resources/s3_bucket_website_configuration.md
  examples/data-sources/cloudavenue_s3_bucket_website_configuration/data-source.tf
  examples/resources/cloudavenue_s3_bucket_website_configuration/import.sh
  go.mod
  go.sum
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/provider/s3/base.go
  internal/provider/s3/bucket_website_configuration_datasource.go
  internal/provider/s3/bucket_website_configuration_resource.go
  internal/provider/s3/bucket_website_configuration_schema.go
  internal/provider/s3/bucket_website_configuration_schema_test.go
  internal/provider/s3/bucket_website_configuration_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/s3_bucket_website_configuration_datasource_test.go
  internal/testsacc/s3_bucket_website_configuration_resource_test.go
  templates/data-sources/s3_bucket_website_configuration.md.tmpl
  templates/resources/s3_bucket_website_configuration.md.tmpl
Labels: Feature, size/XL

#604 feat: new resource/datasource `cloudavenue_s3_bucket_acl`
  .changelog/577.txt
  docs/data-sources/s3_bucket_acl.md
  docs/resources/s3_bucket_acl.md
  examples/data-sources/cloudavenue_s3_bucket_acl/data-source.tf
  examples/resources/cloudavenue_s3_bucket_acl/import.sh
  go.mod
  go.sum
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/provider/s3/bucket_acl_datasource.go
  internal/provider/s3/bucket_acl_resource.go
  internal/provider/s3/bucket_acl_schema.go
  internal/provider/s3/bucket_acl_schema_test.go
  internal/provider/s3/bucket_acl_types.go
  internal/provider/s3/bucket_cors_configuration_resource.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/s3_bucket_acl_datasource_test.go
  internal/testsacc/s3_bucket_acl_resource_test.go
  templates/data-sources/s3_bucket_acl.md.tmpl
  templates/resources/s3_bucket_acl.md.tmpl
Labels: Feature, size/XL, Fix, category/s3

#610 fix: change s3Client after upgrade `cloudavenue-sdk-go` to v0.4.0
  .changelog/609.txt
  go.mod
  go.sum
  internal/provider/s3/bucket_acl_datasource.go
  internal/provider/s3/bucket_acl_resource.go
  internal/provider/s3/bucket_cors_configuration_datasource.go
  internal/provider/s3/bucket_cors_configuration_resource.go
  internal/provider/s3/bucket_datasource.go
  internal/provider/s3/bucket_lifecycle_configuration_datasource.go
  internal/provider/s3/bucket_lifecycle_configuration_resource.go
  internal/provider/s3/bucket_resource.go
  internal/provider/s3/bucket_versioning_configuration_datasource.go
  internal/provider/s3/bucket_versioning_configuration_resource.go
  internal/provider/s3/bucket_website_configuration_datasource.go
  internal/provider/s3/bucket_website_configuration_resource.go
Labels: Fix, size/S

#611 chore: add devcontainer
  .devcontainer/.terraformrc
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: Chore, size/S

#622 chore: upgrade go mod for CMD
  cmd/listing/go.mod
  cmd/listing/go.sum
  cmd/types-generator/go.mod
  cmd/types-generator/go.sum
Labels: Chore, size/L

#619 feat: add sync after s3 bucket created
  .changelog/608.txt
  go.mod
  go.sum
  internal/provider/s3/bucket_resource.go
Labels: Feature, size/XS

#620 fix: lease setting in `cloudavenue_vapp` resource
  .changelog/617.txt
  docs/data-sources/vapp.md
  docs/resources/vapp.md
  internal/provider/common/vdc/vdc.go
  internal/provider/vapp/common_org_network.go
  internal/provider/vapp/vapp_common.go
  internal/provider/vapp/vapp_datasource.go
  internal/provider/vapp/vapp_resource.go
  internal/provider/vapp/vapp_schema.go
  internal/provider/vapp/vapp_types.go
  internal/testsacc/vapp_datasource_test.go
  internal/testsacc/vapp_resource_test.go
Labels: size/L, Fix

#624 chore: add dependabot settings for AWS dependency
  .github/dependabot.yml
Labels: Chore, size/XS

#626 chore: upgrade to terraform-plugin-sdk v2
  go.mod
  go.sum
  internal/provider/s3/bucket_policy_resource.go
  internal/provider/s3/bucket_policy_types.go
Labels: Chore, size/L

#631 feat: refacto `cloudavenue_vcda_ip` to new supertypes/SDK
  .changelog/631.txt
  docs/resources/vcda_ip.md
  go.mod
  go.sum
  internal/provider/vcda/vcda_ip_resource.go
  internal/provider/vcda/vcda_ip_schema.go
  internal/provider/vcda/vcda_ip_types.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/vcda_ip_resource_test.go
Labels: Feature, size/M

#634 feat: add `cloudavenue_s3_user` datasource
  .changelog/633.txt
  docs/data-sources/s3_user.md
  examples/data-sources/cloudavenue_s3_user/data-source.tf
  go.mod
  go.sum
  internal/provider/provider_datasources.go
  internal/provider/s3/credential_resource.go
  internal/provider/s3/user_datasource.go
  internal/provider/s3/user_schema.go
  internal/provider/s3/user_schema_test.go
  internal/provider/s3/user_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/s3_user_datasource_test.go
  templates/data-sources/s3_user.md.tmpl
Labels: Feature, size/M

#635 chore: refacto testsacc `_catalog` datasource
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/catalog_datasource_test.go
  internal/testsacc/catalog_vapp_template_datasource_test.go
  internal/testsacc/catalogs_datasource_test.go
Labels: Chore, size/M

#637 fix: login s3
  .changelog/637.txt
  go.mod
  go.sum
Labels: Fix, size/XS

#642 fix: `_s3_bucket_acl` catch error when bucket read return a error
  .changelog/641.txt
  internal/provider/s3/bucket_acl_resource.go
  internal/provider/s3/bucket_acl_types.go
Labels: Fix, size/XS

#639 chore: refacto test ACC edgegw
  .changelog/639.txt
  docs/resources/edgegateway.md
  docs/resources/edgegateway_firewall.md
  internal/provider/edgegw/edgegateways_datasource.go
  internal/provider/edgegw/edgegateways_schema.go
  internal/provider/edgegw/edgegateways_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/common.go
  internal/testsacc/edgegw_dhcp_forwarding_resource_test.go
  internal/testsacc/edgegw_edgegateway_resource_test.go
  internal/testsacc/edgegw_edgegateways_datasource_test.go
  internal/testsacc/edgegw_firewall_datasource_test.go
  internal/testsacc/edgegw_firewall_resource_test.go
  internal/testsacc/vdc_group_resource_test.go
  internal/testsacc/vdc_resource_test.go
  templates/resources/edgegateway.md.tmpl
  templates/resources/edgegateway_firewall.md.tmpl
Labels: Chore, size/L

#644 chore: Upgrade cloudavenue-sdk-go to v0.5.5
  .changelog/644.txt
  go.mod
  go.sum
  internal/provider/backup/backup_resource.go
  internal/provider/provider.go
Labels: Chore, size/XS

#649 fix: ip not required when ip_allocation_mode is POOL (#647)
  .changelog/649.txt
  docs/resources/vm.md
  internal/provider/vm/vm_schema.go
Labels: Fix, size/XS
