Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-07, with the labels that each got.

#368 feat: add resource/datasource `cloudavenue_edgegateway_security_group`
  .changelog/342.txt
  .changelog/351.txt
  docs/data-sources/edgegateway_security_group.md
  docs/resources/edgegateway_security_group.md
  examples/data-sources/cloudavenue_edgegateway_security_group/data-source.tf
  examples/resources/cloudavenue_edgegateway_security_group/import.sh
  examples/resources/cloudavenue_edgegateway_security_group/resource.tf
  internal/client/vdc.go
  internal/provider/common/edgegw/edgegw.go
  internal/provider/edgegw/edgegateway_resource.go
  internal/provider/edgegw/security_group_datasource.go
  internal/provider/edgegw/security_group_resource.go
  internal/provider/edgegw/security_group_schema.go
  internal/provider/edgegw/security_group_types.go
  internal/provider/provider.go
  internal/tests/edgegw/security_group_datasource_test.go
  internal/tests/edgegw/security_group_resource_test.go
  pkg/utils/utils.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
  templates/data-sources/edgegateway_security_group.md.tmpl
  templates/resources/edgegateway_security_group.md.tmpl
Labels: Feature, size/XL

#372 feat: add resource/datasource `cloudavenue_network_dhcp`
  .changelog/348.txt
  .changelog/349.txt
  cmd/types-generator/elementType.go
  cmd/types-generator/go.mod
  cmd/types-generator/go.sum
  cmd/types-generator/main.go
  cmd/types-generator/schemaType.go
  docs/data-sources/network_dhcp.md
  docs/resources/network_dhcp.md
  examples/data-sources/cloudavenue_network_dhcp/data-source.tf
  examples/resources/cloudavenue_network_dhcp/import.sh
  examples/resources/cloudavenue_network_dhcp/resource.tf
  internal/client/org.go
  internal/provider/network/dhcp_datasource.go
  internal/provider/network/dhcp_resource.go
  internal/provider/network/dhcp_schema.go
  internal/provider/network/dhcp_types.go
  internal/provider/provider.go
  internal/tests/network/dhcp_datasource_test.go
  internal/tests/network/dhcp_resource_test.go
  templates/data-sources/network_dhcp.md.tmpl
  templates/resources/network_dhcp.md.tmpl
Labels: Feature, Chore, size/XL

#381 fix: `resource/cloudavenue_vm_affinity_rule` - Set more than 2VMs IDs
  .changelog/380.txt
  docs/data-sources/vm_affinity_rule.md
  docs/resources/vm_affinity_rule.md
  internal/provider/vm/vm_affinity_rule_datasource.go
  internal/provider/vm/vm_affinity_rule_resource.go
  internal/provider/vm/vm_affinity_rule_schema.go
  internal/tests/vm/vm_affinity_rule_resource_test.go
  templates/resources/vm_affinity_rule.md.tmpl
Labels: Fix, size/S

#385 ci: add codeql scanning
  .github/workflows/codeql.yml
Labels: CI, size/S

#388 chore(script): Change action of codeQL to one time per week
  .github/workflows/codeql.yml
Labels: Chore, size/XS, category/script

#389 fix: bug new cloudavenue publicip return wrong public ip
  internal/provider/publicip/publicip_resource.go
  internal/tests/publicip/publicip_resource_test.go
Labels: Fix, size/XS

#393 chore: Update Code Of Conduct
  .github/CODE_OF_CONDUCT.md
Labels: Chore, size/M

#392 chore: update CodeOwner
  .github/CODEOWNERS
Labels: Chore, size/XS

#384 refactor: schema medias catalog
  .changelog/384.txt
  docs/data-sources/catalog_medias.md
  internal/provider/catalog/media_schema.go
  internal/provider/catalog/medias_datasource.go
  internal/provider/catalog/medias_schema.go
Labels: Refactor, size/M, category/catalog

#375 chore(catalog): Refactor schema/types
  internal/provider/catalog/catalog_schema.go
  internal/provider/catalog/catalog_types.go
  internal/provider/catalog/catalog_vapp_template_datasource.go
  internal/provider/catalog/catalog_vapp_template_schema.go
  internal/provider/catalog/catalog_vapp_template_types.go
  internal/provider/catalog/catalogs_datasource.go
  internal/provider/catalog/catalogs_schema.go
  internal/provider/catalog/catalogs_types.go
  internal/provider/catalog/media_schema.go
  internal/provider/catalog/media_types.go
  internal/provider/catalog/medias_datasource.go
  internal/provider/catalog/medias_schema.go
  internal/provider/catalog/medias_types.go
Labels: Chore, size/M, category/catalog

#394 chore: add cmd types-generator
  .vscode/changelog.code-snippets
  .vscode/terraform.code-snippets
  cmd/types-generator/go.mod
  cmd/types-generator/go.sum
  cmd/types-generator/main.go
  cmd/types-generator/schemaType.go
  go.mod
  go.sum
  main.go
  pkg/utils/utils.go
Labels: Chore, size/L

#395 chore(iam): Add schema/types
  internal/provider/iam/right_datasource.go
  internal/provider/iam/right_schema.go
  internal/provider/iam/right_types.go
  internal/provider/iam/role_schema.go
  internal/provider/iam/role_types.go
  internal/provider/iam/user_schema.go
  internal/provider/iam/user_types.go
Labels: Chore, size/M, category/iam

#399 chore(publicip): Add schema/types
  internal/provider/publicip/publicip_schema.go
  internal/provider/publicip/publicip_types.go
  internal/provider/publicip/publicips_datasource.go
  internal/provider/publicip/publicips_schema.go
  internal/provider/publicip/publicips_types.go
Labels: Chore, size/M, category/publicip

#398 chore(storage): Add schema/types
  internal/provider/storage/profile_datasource.go
  internal/provider/storage/profile_schema.go
  internal/provider/storage/profile_types.go
  internal/provider/storage/profiles_datasource.go
  internal/provider/storage/profiles_schema.go
  internal/provider/storage/profiles_types.go
Labels: Chore, size/M, category/storage

#373 feat: add resource/datasource `cloudavenue_network_dhcp_binding`
  .changelog/357.txt
  .changelog/358.txt
  docs/data-sources/network_dhcp_binding.md
  docs/resources/network_dhcp_binding.md
  examples/data-sources/cloudavenue_network_dhcp_binding/data-source.tf
  examples/resources/cloudavenue_network_dhcp_binding/import.sh
  examples/resources/cloudavenue_network_dhcp_binding/resource.tf
  go.mod
  internal/provider/network/dhcp_binding_datasource.go
  internal/provider/network/dhcp_binding_resource.go
  internal/provider/network/dhcp_binding_schema.go
  internal/provider/network/dhcp_binding_schema_test.go
  internal/provider/network/dhcp_binding_types.go
  internal/provider/provider.go
  internal/tests/network/dhcp_binding_datasource_test.go
  internal/tests/network/dhcp_binding_resource_test.go
  pkg/utils/utils.go
  templates/data-sources/network_dhcp_binding.md.tmpl
  templates/resources/network_dhcp_binding.md.tmpl
Labels: Feature, size/XL

#406 chore: migrate `cloudavenue_iam_right` datasource to SuperSchema/Supertypes
  cmd/types-generator/main.go
  internal/provider/iam/right_datasource.go
  internal/provider/iam/right_schema.go
  internal/provider/iam/right_types.go
  internal/tests/iam/iam_right_datasource_test.go
Labels: Chore, size/L

#404 chore(edgegw): Add schema/types
  internal/provider/edgegw/app_port_profile_resource.go
  internal/provider/edgegw/app_port_profile_schema.go
  internal/provider/edgegw/app_port_profile_type.go
  internal/provider/edgegw/edgegateway_schema.go
  internal/provider/edgegw/edgegateway_types.go
  internal/provider/edgegw/edgegateways_datasource.go
  internal/provider/edgegw/edgegateways_schema.go
  internal/provider/edgegw/edgegateways_types.go
  internal/provider/edgegw/firewall_resource.go
  internal/provider/edgegw/firewall_types.go
  internal/tests/edgegw/edgegateway_resource_test.go
Labels: Chore, size/M, category/edgegw

#416 chore: fix bug in workflow listingrd
  .github/workflows/generate_listing.yml
  cmd/listing/go.mod
  cmd/listing/go.sum
  cmd/listing/main.go
Labels: Chore, CI, size/XS

#415 chore(vdc): Add schema/types
  internal/provider/vdc/acl_schema.go
  internal/provider/vdc/acl_types.go
  internal/provider/vdc/vdc_group_datasource.go
  internal/provider/vdc/vdc_group_types.go
  internal/provider/vdc/vdc_schema.go
  internal/provider/vdc/vdc_types.go
  internal/provider/vdc/vdcs_datasource.go
  internal/provider/vdc/vdcs_schema.go
  internal/provider/vdc/vdcs_types.go
Labels: Chore, size/M, category/vdc

#418 chore(alb): Add types
  internal/provider/alb/pool_schema.go
  internal/provider/alb/pool_types.go
Labels: Chore, size/S, category/alb

#419 chore(vrf): Add types/schema
  internal/provider/vrf/tier0_vrf_datasource.go
  internal/provider/vrf/tier0_vrf_schema.go
  internal/provider/vrf/tier0_vrf_types.go
  internal/provider/vrf/tier0_vrfs_datasource.go
  internal/provider/vrf/tier0_vrfs_schema.go
  internal/provider/vrf/tier0_vrfs_types.go
Labels: Chore, size/M, category/vrf

#424 fix: `cloudavenue_vcda_ip` ID in import
  internal/provider/vcda/vcda_ip_resource.go
Labels: Fix, size/XS

#420 fix: `cloudavenue_vapp_*` units tests and improve example
  .changelog/407.txt
  docs/resources/iam_user.md
  docs/resources/vapp.md
  docs/resources/vapp_acl.md
  docs/resources/vapp_org_network.md
  examples/resources/cloudavenue_iam_user/resource.tf
  examples/resources/cloudavenue_vapp/resource.tf
  examples/resources/cloudavenue_vapp_acl/resource.tf
  examples/resources/cloudavenue_vapp_org_network/resource.tf
  internal/provider/vapp/acl_resource.go
  internal/provider/vapp/acl_schema.go
  internal/tests/iam/iam_user_datasource_test.go
  internal/tests/iam/iam_user_resource_test.go
  internal/tests/vapp/acl_resource_test.go
  internal/tests/vapp/org_network_resource_test.go
  internal/tests/vapp/vapp_resource_test.go
Labels: Fix, size/M, Docs

#430 chore: add resources in list and fix CI errors
  .github/workflows/generate_listing.yml
  cmd/listing/main.go
  cmd/listing/resource-ca.md
  cmd/types-generator/go.mod
  cmd/types-generator/go.sum
  go.mod
  go.sum
  main.go
Labels: Chore, size/L, CI

#408 chore(vapp): Add schema/types
  internal/provider/vapp/acl_schema.go
  internal/provider/vapp/acl_types.go
  internal/provider/vapp/isolated_network_datasource.go
  internal/provider/vapp/isolated_network_resource.go
  internal/provider/vapp/isolated_network_schema.go
  internal/provider/vapp/isolated_network_types.go
  internal/provider/vapp/vapp_schema.go
  internal/provider/vapp/vapp_types.go
Labels: Chore, size/M, category/vapp

#432 ci: Add GoTests.yml
  .github/workflows/generate.yml
  .github/workflows/generate_listing.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: CI, size/S

#431 feat: add resource/datasource `cloudavenue_edgegateway_static_route`
  .changelog/427.txt
  .changelog/428.txt
  .changelog/431.txt
  cmd/listing/main.go
  cmd/listing/resource-ca.md
  docs/data-sources/edgegateway_ip_set
  docs/data-sources/edgegateway_ip_set.md
  docs/data-sources/edgegateway_static_route.md
  docs/resources/edgegateway_ip_set.md
  docs/resources/edgegateway_static_route.md
  examples/data-sources/cloudavenue_edgegateway_ip_set/data-source.tf
  examples/data-sources/cloudavenue_edgegateway_static_route/data-source.tf
  examples/resources/cloudavenue_edgegateway_ip_set/resource.tf
  examples/resources/cloudavenue_edgegateway_static_route/import.sh
  examples/resources/cloudavenue_edgegateway_static_route/resource.tf
  go.mod
  go.sum
  internal/provider/edgegw/static_route_datasource.go
  internal/provider/edgegw/static_route_resource.go
  internal/provider/edgegw/static_route_schema.go
  internal/provider/edgegw/static_route_types.go
  internal/provider/provider.go
  internal/tests/edgegw/static_route_datasource_test.go
  internal/tests/edgegw/static_route_resource_test.go
  main.go
  pkg/uuid/uuid.go
  templates/data-sources/edgegateway_ip_set.md.tmpl
  templates/data-sources/edgegateway_static_route.md.tmpl
  templates/resources/edgegateway_static_route.md.tmpl
Labels: Feature, Chore, size/XL, Fix, category/script
