Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2023-06, with the labels that each got.

#312 fix: unlock in append diags function
  internal/provider/vapp/acl_resource.go
Labels: Fix, size/XS

#318 ci: add dependencies between jobs
  .github/workflows/release.yml
Labels: CI, size/XS

#320 feat: add import for `cloudavenue_vm`
  .changelog/320.txt
  docs/resources/vm.md
  examples/resources/cloudavenue_vm/import.sh
  internal/provider/common/vm/settings.go
  internal/provider/common/vm/settings_customization.go
  internal/provider/common/vm/settings_guest_properties.go
  internal/provider/vm/vm_resource.go
  internal/provider/vm/vm_schema.go
  internal/tests/vm/vm_resource_test.go
Labels: Feature, Chore, Fix, size/M, Docs

#294 feat(vm): Init security tag ressource
  .changelog/294.txt
  docs/resources/vm_security_tag.md
  examples/resources/cloudavenue_vm_security_tag/import.sh
  examples/resources/cloudavenue_vm_security_tag/resource.tf
  internal/provider/provider.go
  internal/provider/vm/security_tag_resource.go
  internal/provider/vm/security_tag_schema.go
  internal/tests/vm/security_tag_resource_test.go
  templates/resources/vm_security_tag.md.tmpl
Labels: Feature, size/L, Fix, Docs, category/vm

#323 ci: fix goreleaser to generate changelog in release
  .goreleaser.yml
Labels: CI, size/XS

#321 docs: add documentation for cold update attributes (`cloudavenue_vm`)
  .changelog/308.txt
  docs/resources/vm.md
  internal/provider/vm/vm_schema.go
  templates/resources/vm.md.tmpl
Labels: size/M, Docs

#325 feat: add resource `cloudavenue_network_app_port_profile`
  .changelog/319.txt
  docs/resources/network_app_port_profile.md
  examples/resources/cloudavenue_network_app_port_profile/import.sh
  examples/resources/cloudavenue_network_app_port_profile/resource.tf
  internal/provider/network/app_port_profile_resource.go
  internal/provider/provider.go
  internal/tests/network/app_port_profile_resource_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  templates/resources/network_app_port_profile.md.tmpl
Labels: Feature, Chore, size/L

#326 feat: add datasource `cloudavenue_storage_profile`
  .changelog/326.txt
  docs/data-sources/storage_profile.md
  examples/data-sources/cloudavenue_storage_profile/data-source.tf
  internal/provider/common/vdc/storage_profile.go
  internal/provider/provider.go
  internal/provider/storage/base.go
  internal/provider/storage/profile_datasource.go
  internal/tests/storage/profile_datasource_test.go
  templates/data-sources/storage_profile.md.tmpl
Labels: Feature, Chore, Fix, size/M

#330 chore: add normalize Vmware UUID
  internal/provider/common/acl/acl.go
  internal/provider/common/common.go
  internal/provider/edgegw/edgegateway_datasource.go
  internal/provider/edgegw/edgegateway_resource.go
  internal/provider/edgegw/edgegateways_datasource.go
  internal/provider/network/app_port_profile_resource.go
  internal/provider/vapp/isolated_network_datasource.go
  internal/provider/vapp/isolated_network_resource.go
  internal/provider/vapp/org_network_datasource.go
  internal/provider/vapp/org_network_resource.go
  internal/provider/vdc/vdc_datasource.go
  internal/provider/vdc/vdc_resource.go
  internal/provider/vm/vm_affinity_rule_resource.go
  internal/provider/vm/vm_resource.go
  internal/tests/alb/pool_datasource_test.go
  internal/tests/alb/pool_resource_test.go
  internal/tests/edgegw/edgegateway_datasource_test.go
  internal/tests/edgegw/edgegateway_resource_test.go
  internal/tests/edgegw/edgegateways_datasource_test.go
  internal/tests/network/isolated_resource_test.go
  internal/tests/network/routed_datasource_test.go
  internal/tests/network/routed_resource_test.go
  internal/tests/storage/profile_datasource_test.go
  internal/tests/vapp/acl_resource_test.go
  internal/tests/vapp/isolated_network_datasource_test.go
  internal/tests/vapp/isolated_network_resource_test.go
  internal/tests/vapp/org_network_datasource_test.go
  internal/tests/vdc/acl_resource_test.go
  internal/tests/vdc/vdc_datasource_test.go
  internal/tests/vdc/vdc_resource_test.go
  internal/tests/vm/security_tag_resource_test.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
Labels: Chore, size/L

#333 chore: add snippets for changelog
  .vscode/terraform.code-snippets
Labels: Chore, size/S

#335 feat: add `cloudavenue_vcda_ip` resource
  .changelog/335.txt
  docs/resources/vcda_ip.md
  internal/provider/provider.go
  internal/provider/vcda/vcda_ip_resource.go
  internal/tests/vcda/vcda_ip_resource_test.go
  pkg/uuid/uuid.go
  templates/resources/vcda_ip.md.tmpl
Labels: Feature, Chore, Fix, size/M, Docs

#336 feat: add `cloudavenue_publicip` resource
  .changelog/336.txt
  docs/resources/publicip.md
  examples/resources/cloudavenue_publicip/resource.tf
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/publicip/publicip_resource.go
  internal/provider/publicip/publicip_schema.go
  internal/tests/publicip/publicip_resource_test.go
  templates/resources/publicip.md.tmpl
Labels: Feature, Chore, size/M, Docs

#322 feat: new data source `cloudavenue_vm`
  .changelog/322.txt
  docs/data-sources/vm.md
  docs/resources/vm.md
  examples/data-sources/cloudavenue_vm/data-source.tf
  internal/provider/provider.go
  internal/provider/vm/vm_datasource.go
  internal/provider/vm/vm_schema.go
  internal/tests/vm/vm_datasource_test.go
  templates/data-sources/vm.md.tmpl
Labels: Feature, Chore, size/L, Fix

#341 feat: add `cloudavenue_edgegateway_firewall` resource/datasource
  .changelog/340.txt
  docs/data-sources/edgegateway_firewall.md
  docs/resources/edgegateway_firewall.md
  docs/resources/network_app_port_profile.md
  examples/data-sources/cloudavenue_network_firewall/data-source.tf
  examples/resources/cloudavenue_edgegateway_firewall/import.sh
  examples/resources/cloudavenue_edgegateway_firewall/resource.tf
  examples/resources/cloudavenue_network_app_port_profile/import.sh
  internal/provider/edgegw/firewall_datasource.go
  internal/provider/edgegw/firewall_resource.go
  internal/provider/edgegw/firewall_schema.go
  internal/provider/provider.go
  internal/tests/common/acctest.go
  internal/tests/edgegw/firewall_datasource_test.go
  internal/tests/edgegw/firewall_resource_test.go
  templates/data-sources/edgegateway_firewall.md.tmpl
  templates/resources/edgegateway_firewall.md.tmpl
Labels: Feature, Chore, size/XL, Fix, Docs

#345 fix: snippet new datasource
  .vscode/terraform.code-snippets
Labels: Fix, size/XS

#347 fix: Change resource `cloudavenue_network_app_port_profile` to `cloudavenue_edgegateway_app_port_profile`
  .changelog/347.txt
  docs/resources/edgegateway_app_port_profile.md
  examples/resources/cloudavenue_edgegateway_app_port_profile/import.sh
  examples/resources/cloudavenue_edgegateway_app_port_profile/resource.tf
  examples/resources/cloudavenue_network_app_port_profile/import.sh
  internal/provider/edgegw/app_port_profile_resource.go
  internal/provider/provider.go
  internal/tests/edgegw/app_port_profile_resource_test.go
  templates/resources/edgegateway_app_port_profile.md.tmpl
Labels: Chore, Fix, size/XS

#364 feat: add cmd types generator
  cmd/types-generator/attributeType.go
  cmd/types-generator/elementType.go
  cmd/types-generator/go.mod
  cmd/types-generator/go.sum
  cmd/types-generator/main.go
  cmd/types-generator/schemaType.go
  cmd/types-generator/types.go.tmpl
Labels: Feature, size/L

#365 fix: bug in org_network_resource vapp undeploy
  .changelog/365.txt
  internal/provider/vapp/org_network_resource.go
Labels: Chore, Fix, size/XS
