Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2025-07, with the labels that each got.

#1128 refactor: testacc resource and datasource of vpn ip sec
  .changelog/1125.txt
  docs/data-sources/edgegateway_vpn_ipsec.md
  docs/resources/edgegateway_vpn_ipsec.md
  examples/data-sources/cloudavenue_edgegateway_vpn_ipsec/data-source.tf
  examples/resources/cloudavenue_edgegateway_vpn_ipsec/resource.tf
  examples/resources/cloudavenue_edgegateway_vpn_ipsec/resource_with_custom_properties.tf
  internal/provider/provider.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/edgegw_vpn_ipsec_datasource_test.go
  internal/testsacc/edgegw_vpn_ipsec_resource_test.go
  templates/resources/edgegateway_vpn_ipsec.md.tmpl
Labels: size/L, refactor

#1135 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: size/S, sync, chore

#1148 fix: bug update `_elb_virtual_service` ress if service engine is set
  .changelog/1142.txt
  .golangci.yml
  internal/provider/elb/virtual_service_schema.go
  internal/provider/elb/virtual_service_types.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/elb_service_engine_group_datasource_test.go
  internal/testsacc/elb_service_engine_groups_datasource_test.go
  internal/testsacc/elb_virtual_service_resource_test.go
Labels: size/S, fix

#1149 chore: synced file(s) with orange-cloudavenue/workflows
  .golangci.yml
Labels: size/XS, sync, chore
