Repository orange-cloudavenue/terraform-provider-cloudavenue, pull requests merged in 2025-04, with the labels that each got.

#1057 chore: synced file(s) with orange-cloudavenue/workflows
  .golangci.yml
  .pre-commit-config.yaml
Labels: size/M, sync, chore

#1065 feat: add ress/data `cloudavenue_edgegateway_services`
  .changelog/1037.txt
  .changelog/1069.txt
  docs/data-sources/edgegateway_services.md
  docs/resources/edgegateway.md
  docs/resources/edgegateway_services.md
  examples/data-sources/cloudavenue_edgegateway_services/data-source.tf
  examples/resources/cloudavenue_edgegateway_services/resource.tf
  go.mod
  go.sum
  internal/provider/edgegw/edgegateway_resource.go
  internal/provider/edgegw/edgegateway_schema.go
  internal/provider/edgegw/services_datasource.go
  internal/provider/edgegw/services_resource.go
  internal/provider/edgegw/services_schema.go
  internal/provider/edgegw/services_schema_test.go
  internal/provider/edgegw/services_types.go
  internal/provider/provider_datasources.go
  internal/provider/provider_resources.go
  internal/testsacc/acctest_datasources_test.go
  internal/testsacc/acctest_resources_test.go
  internal/testsacc/edgegw_services_datasource_test.go
  internal/testsacc/edgegw_services_resource_test.go
  templates/data-sources/edgegateway_services.md.tmpl
  templates/resources/edgegateway_services.md.tmpl
Labels: size/L, feature

#1074 fix: create T1 if T0 dedicated
  .changelog/1069.txt
  docs/resources/edgegateway.md
Labels: size/XS, fix

#1076 fix: bugs #1071 #1073 #1064
  .changelog/1064.txt
  .changelog/1071.txt
  .changelog/1073.txt
  cmd/edgegateway-doc/main.go
  docs/resources/edgegateway.md
  internal/provider/edgegw/edgegateway_schema.go
  internal/provider/edgegw/network_routed_resource.go
Labels: size/S, fix

#1060 chore!: remove attribute owner_type for resource/datasource cloudavenue_edgegateway
  .changelog/952.txt
  docs/data-sources/edgegateway.md
  docs/data-sources/edgegateways.md
  docs/resources/edgegateway.md
  internal/provider/edgegw/edgegateway_datasource.go
  internal/provider/edgegw/edgegateway_resource.go
  internal/provider/edgegw/edgegateway_schema.go
  internal/provider/edgegw/edgegateway_types.go
  internal/provider/edgegw/edgegateways_datasource.go
  internal/provider/edgegw/edgegateways_schema.go
  internal/provider/edgegw/edgegateways_types.go
  internal/testsacc/edgegw_edgegateway_resource_test.go
Labels: size/S, breaking-change, chore, breaking change

#1082 fix: vdcg_network_routed unexpectedly null to empty
  .changelog/1081.txt
  internal/provider/vdcg/network_routed_resource.go
Labels: size/XS, fix

#1080 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/release.yml
Labels: size/XS, sync, chore
